version: '3.8'

services:
  db:
    image: postgres:16
    container_name: authentication-service-container
    environment:
      POSTGRES_DB: authentication-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-db-data:/data/postgres
    ports:
      - "5433:5432"